# Omakase Ruby styling for Rails
# inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

require:
  - rubocop-graphql

AllCops:
  NewCops: disable

Bundler:
  Enabled: false

Layout:
  Enabled: false

Lint:
  Enabled: false

Metrics:
  Enabled: false

Naming:
  Enabled: false

Style:
  Enabled: false
